stages:
  - build
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-job:
  stage: build
  image: openjdk:8-slim
  only:
    - tags
    - web
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew
  script:
    - ./gradlew build
    - mv build/libs/LOTR-UCP-*jar ./
    - rm -rf build/libs
  artifacts:
    name: "$CI_COMMIT_TAG"
    paths:
      - ./LOTR-UCP-*.jar
  cache:
    key: "master-cache"
    policy: pull-push
    paths:
      - build
      - .gradle
      
deploy-job:
  stage: deploy
  image: curlimages/curl
  only:
    - tags
    - web
  variables:
    #You can't have spaces in the variables as that messed up the curl
    HEADER: "PRIVATE-TOKEN:$PRIVATE_TOKEN"
    DATA_NAME: "Download_v$CI_COMMIT_TAG"
    DATA_URL: "https://gitlab.com/DwarfyAssassin/LOTRUCP/-/jobs/artifacts/$CI_COMMIT_TAG/raw/LOTR-UCP-$CI_COMMIT_TAG.jar?job=build-job"
    API_URL: "$CI_API_V4_URL/projects/16170860/releases/$CI_COMMIT_TAG/assets/links"
  script:
    - curl --request POST --header $HEADER --data name=$DATA_NAME --data url=$DATA_URL $API_URL